### ISSUE TITLE
Image Optimization Lambda: Allow for defining a bucket key prefix

### ISSUE THREAD

**Issue by pinarruiz** [serverless-stack/open-next#65]
Something like an environment variable like `BUCKET_KEY_PREFIX` that will make the function search on `/process.env.BUCKET_KEY_PREFIX/...` if defined.

This allows for more complex architectures and rollover of the public folder.

**Comment by pinarruiz** [comment]
I did not explain the favicon correctly, I have all the assets under `public/assets` so that will be `/assets` on the bucket, and then we configure it with the html tag and specify it is on `/assets/favicon.ico`, I do this so i do not need to set up any fallback and the assets all come from the same path, with the origin configured with a path that matches the prefix so both `/assets` and `/_next/static/*` get answered correctly.

**Comment by fwang** [comment]
Ah I see, getting the deployments to be more atomic.

The origin path is only configured for the `/assets` and `/_next/static/*` behaviours, not the ssr/api/image routes right?

It'd be great if you can share your CloudFront configuration here. I think many team would be attracted to this architecture.

**Comment by pinarruiz** [comment]
> The origin path is only configured for the S3 origin (ie. /assets and /_next/static/*), not the URL origins (ie. ssr/api/image) right?

Yeah, only configured on the S3 origin, the behaviours are as expected.

> It'd be great if you can share your CloudFront configuration here. I will keep this issue around. I'm sure many teams would be attracted to this architecture.

Sure, I use a python script to update the Cloudfront configuration just because I want some extra actions to be done and i found it easier this way, regardless of that, the configuration looks like:

```yaml
CloudFrontDistribution:
  Type: AWS::CloudFront::Distribution
  Properties:
    DistributionConfig:
      Enabled: true
      HttpVersion: "http2"
      DefaultCacheBehavior:
        TargetOriginId: "serverlambda"
        ViewerProtocolPolicy: "redirect-to-https"
        Compress: true
        CachePolicyId: ...
        AllowedMethods: ...
      CacheBehaviors:
        - TargetOriginId: "assetsbucket"
          PathPattern: "/_next/static/*"
          ViewerProtocolPolicy: "redirect-to-https"
          Compress: true
          CachePolicyId: ...
          AllowedMethods: ...

        - TargetOriginId: "imagelambda"
          PathPattern: "/_next/image"
          ViewerProtocolPolicy: "redirect-to-https"
          Compress: true
          CachePolicyId: ...
          AllowedMethods: ...

        - TargetOriginId: "serverlambda"
          PathPattern: "/_next/data/*"
          ViewerProtocolPolicy: "redirect-to-https"
          Compress: true
          CachePolicyId: ...
          AllowedMethods: ...

        - TargetOriginId: "serverlambda"
          PathPattern: "/api/*"
          ViewerProtocolPolicy: "redirect-to-https"
          Compress: true
          CachePolicyId: ...
          AllowedMethods: ...

        - TargetOriginId: "assetsbucket"
          PathPattern: "/assets/*"
          ViewerProtocolPolicy: "redirect-to-https"
          Compress: true
          CachePolicyId: ...
          AllowedMethods: ...

      Origins:
        - Id: "assetsbucket"
          OriginPath: "/${prefixvariable}"
          DomainName:
            Fn::GetAtt: [AssetsBucket, RegionalDomainName]
          S3OriginConfig:
            OriginAccessIdentity:
              Fn::Join:
                - ""
                - - "origin-access-identity/cloudfront/"
                  - !Ref CloudFrontDistributionOriginAccessIdentity
        - Id: "serverlambda"
          CustomOriginConfig:
            OriginProtocolPolicy: "https-only"
            OriginSSLProtocols:
              - TLSv1.2
          DomainName:
            Fn::Select:
              - 2
              - Fn::Split:
                - "/"
                - !GetAtt ServerLambdaUrl.FunctionUrl
        - Id: "imagelambda"
          CustomOriginConfig:
            OriginProtocolPolicy: "https-only"
            OriginSSLProtocols:
              - TLSv1.2
          DomainName:
            Fn::Select:
              - 2
              - Fn::Split:
                - "/"
                - !GetAtt ImageoptimizationLambdaUrl.FunctionUrl
```

I have not included how i upload the assets to the bucket but first i upload them to the prefix key in my case this key is the commit sha, and once uploaded and everything has been swapped the old assets are removed too. I use [S3 Sync](https://github.com/k1LoW/serverless-s3-sync) to upload and remove assets.

Let me know if i am missing something to share about the configuration.
